apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: redis
  name: argocd-redis
spec:
  serviceName: argocd-redis
  replicas: 6
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      serviceAccountName: argocd-redis  
      containers:
      - name: redis
        image: redis:5.0.1-alpine
        imagePullPolicy: Always
        args:
        - "--save"
        - ""
        - "--appendonly"
        - "no"
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
        #   name: gossip
        # command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
  #       env:
  #       - name: POD_IP
  #         valueFrom:
  #           fieldRef:
  #             fieldPath: status.podIP
  #       volumeMounts:
  #       - name: conf
  #         mountPath: /conf
  #         readOnly: false
  #       - name: data
  #         mountPath: /data
  #         readOnly: false
  #     volumes:
  #     - name: conf
  #       configMap:
  #         name: redis-cluster
  #         defaultMode: 0755
  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-redis
              topologyKey: kubernetes.io/hostname
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/part-of: argocd
              topologyKey: kubernetes.io/hostname     