apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000  
        runAsUser: 0          
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts          #-jdk11
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000  
        resources:     
            requests:
              memory: 1000Mi
              cpu: "700m"
            limits:
              memory: 2000Mi
              cpu: "750m"     
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/bash
        #     - -ec
            
        #   failureThreshold: 6
        #   initialDelaySeconds: 120
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 20  

        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/bash
        #     - -ec
            
        #   failureThreshold: 3
        #   initialDelaySeconds: 10
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 20    
#         livenessProbe:
#             httpGet:
#               path: /
#               port: 80
#             initialDelaySeconds: 60
#             periodSeconds: 10
#             timeoutSeconds: 5
#             failureThreshold: 5
#         readinessProbe:
#             httpGet:
#               path: /
#               port: 80
#             initialDelaySeconds: 60
#             periodSeconds: 10
#             timeoutSeconds: 5
#             failureThreshold: 3       
      #   volumeMounts:
      #     - name: jenkins-vol
      #       mountPath: /var/jenkins_home 
      # volumes:
      #   - name: jenkins-vol
      #     persistentVolumeClaim:
      #       claimName: jenkins-pv-claim

   


